Webhint give errors, see second comment
Run npx hint .
  npx hint .
  shell: /bin/bash -e {0}
  env:
    FORCE_COLOR: 1
Error: Cannot find module '@hint/utils-dom'
Require stack:
- /home/runner/work/portfolio/portfolio/node_modules/hint/dist/src/lib/hint-context.js
- /home/runner/work/portfolio/portfolio/node_modules/hint/dist/src/lib/engine.js
- /home/runner/work/portfolio/portfolio/node_modules/hint/dist/src/lib/index.js
- /home/runner/work/portfolio/portfolio/node_modules/hint/dist/src/lib/cli/analyze.js
- /home/runner/work/portfolio/portfolio/node_modules/hint/dist/src/lib/cli/actions.js